// Datos de demostración para cuando Supabase no está configurado
export const SEED_ANIMALS = [
  { id: '1', type: 'perdido', species: 'perro', name: 'Coco', breed: 'Labrador', color: 'Amarillo', size: 'grande', age: '3 años', gender: 'macho', zone: 'Barrio San Bernardo', address: 'Av. Entre Ríos y Mitre', lat: -24.785, lng: -65.412, date: '2025-05-06', reward: 'Sí – $15.000', description: 'Se escapó por la puerta delantera. Muy cariñoso, usa collar rojo. Responde al nombre Coco.', phone: '387-4521890', photos: ['https://images.unsplash.com/photo-1552053831-71594a27632d?w=300&q=60&auto=format&fit=crop'], user: 'María González', userId: '1', likes: 24, views: 187, verified: true, source: 'manual' },
  { id: '2', type: 'adopcion', species: 'gato', name: 'Luna', breed: 'Mestizo', color: 'Gris y blanco', size: 'pequeño', age: '1 año', gender: 'hembra', zone: 'Barrio Tres Ceibos', address: 'Bº Tres Ceibos, Salta', lat: -24.798, lng: -65.401, date: '2025-05-05', reward: null, description: 'Luna es muy tranquila, ya está vacunada y castrada. Ideal para departamento. Busca familia amorosa.', phone: '387-4123456', photos: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300&q=60&auto=format&fit=crop'], user: 'Protectora Patitas Salta', userId: '2', likes: 41, views: 312, verified: true, source: 'ong' },
  { id: '3', type: 'encontrado', species: 'perro', name: 'Sin nombre', breed: 'Mestizo', color: 'Negro y café', size: 'mediano', age: 'Joven', gender: 'macho', zone: 'Centro Salta', address: 'Caseros y Zuviría', lat: -24.787, lng: -65.409, date: '2025-05-07', reward: null, description: 'Encontré este perrito deambulando solo por el centro. Parece estar bien alimentado. Busco a su dueño.', phone: '387-5678901', photos: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=300&q=60&auto=format&fit=crop'], user: 'Carlos Ríos', userId: '3', likes: 9, views: 78, verified: false, source: 'manual' },
  { id: '4', type: 'perdido', species: 'gato', name: 'Michi', breed: 'Siamés', color: 'Crema y marrón', size: 'pequeño', age: '4 años', gender: 'macho', zone: 'Barrio San Lorenzo', address: 'San Lorenzo, Salta Capital', lat: -24.793, lng: -65.428, date: '2025-05-04', reward: 'Sí – $10.000', description: 'Michi es un gato siamés con ojos azules muy especiales. Se escapó por la ventana. Muy asustadizo.', phone: '387-4098765', photos: ['https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=300&q=60&auto=format&fit=crop'], user: 'Ana Pérez', userId: '4', likes: 33, views: 245, verified: true, source: 'manual' },
  { id: '5', type: 'adopcion', species: 'perro', name: 'Rocky', breed: 'Pitbull mestizo', color: 'Blanco y marrón', size: 'grande', age: '2 años', gender: 'macho', zone: 'Villa Las Rosas', address: 'Bº Villa Las Rosas, Salta', lat: -24.801, lng: -65.389, date: '2025-05-03', reward: null, description: 'Rocky fue rescatado de la calle. Ya está vacunado, desparasitado y esterilizado. Muy juguetón y leal.', phone: '387-4567890', photos: ['https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=300&q=60&auto=format&fit=crop'], user: 'SOS Animal Salta', userId: '5', likes: 58, views: 421, verified: true, source: 'ong' },
  { id: '6', type: 'perdido', species: 'perro', name: 'Nala', breed: 'Golden Retriever', color: 'Dorado', size: 'grande', age: '5 años', gender: 'hembra', zone: 'Barrio Limache', address: 'Av. Limache, Salta', lat: -24.775, lng: -65.419, date: '2025-05-07', reward: 'Sí – $20.000', description: 'Nala se asustó con los fuegos artificiales y escapó. Tiene microchip. Muy dócil.', phone: '387-4312567', photos: ['https://images.unsplash.com/photo-1591160690555-5d7ca0975a4e?w=300&q=60&auto=format&fit=crop'], user: 'Familia Rodríguez', userId: '6', likes: 67, views: 534, verified: true, source: 'manual' },
  { id: '7', type: 'adopcion', species: 'gato', name: 'Tigre', breed: 'Atigrado', color: 'Naranja y negro', size: 'mediano', age: '2 años', gender: 'macho', zone: 'Barrio Limache', address: 'Bº Limache Norte, Salta', lat: -24.774, lng: -65.421, date: '2025-05-02', reward: null, description: 'Tigre llegó a nuestra casa hace 6 meses. Ya está castrado y vacunado. Muy independiente pero cariñoso.', phone: '387-4445566', photos: ['https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?w=300&q=60&auto=format&fit=crop'], user: 'Laura Medina', userId: '7', likes: 29, views: 198, verified: false, source: 'manual' },
  { id: '8', type: 'encontrado', species: 'perro', name: 'Sin nombre', breed: 'Mestizo pequeño', color: 'Blanco', size: 'pequeño', age: 'Adulto', gender: 'hembra', zone: 'Barrio Palermo', address: 'Bº Palermo, Salta Capital', lat: -24.812, lng: -65.405, date: '2025-05-06', reward: null, description: 'Encontré esta perrita blanca en Bº Palermo. Parece perdida. Está limpia y tiene collar pero sin chapa.', phone: '387-4231890', photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&q=60&auto=format&fit=crop'], user: 'Sergio Villalba', userId: '8', likes: 15, views: 132, verified: false, source: 'manual' },
  { id: '9', type: 'perdido', species: 'perro', name: 'Max', breed: 'Beagle', color: 'Tricolor', size: 'mediano', age: '2 años', gender: 'macho', zone: 'Barrio Santa Ana', address: 'Santa Ana, Salta Capital', lat: -24.768, lng: -65.398, date: '2025-05-05', reward: 'Sí – $12.000', description: 'Max salió por el portón trasero que quedó abierto. Tiene collar azul y placa con nombre.', phone: '387-4876543', photos: ['https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=300&q=60&auto=format&fit=crop'], user: 'Pedro Mamani', userId: '9', likes: 44, views: 367, verified: true, source: 'manual' },
  { id: '10', type: 'adopcion', species: 'perro', name: 'Chloe', breed: 'Caniche toy', color: 'Crema', size: 'pequeño', age: '1 año', gender: 'hembra', zone: 'Barrio Primavera', address: 'Bº Primavera, Salta', lat: -24.806, lng: -65.395, date: '2025-04-30', reward: null, description: 'Chloe necesita un hogar porque nos mudamos a un departamento sin mascotas. Está vacunada y desparasitada.', phone: '387-4567123', photos: ['https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=300&q=60&auto=format&fit=crop'], user: 'Valeria Torres', userId: '10', likes: 76, views: 589, verified: true, source: 'ong' },
  { id: '11', type: 'perdido', species: 'gato', name: 'Bella', breed: 'Persa', color: 'Blanco', size: 'mediano', age: '3 años', gender: 'hembra', zone: 'Centro Histórico', address: 'Alberdi y España, Salta', lat: -24.784, lng: -65.408, date: '2025-05-07', reward: 'Sí – $8.000', description: 'Bella es una gata persa blanca con ojos verdes. Se escapó por la terraza. Es tímida con extraños.', phone: '387-4902345', photos: ['https://images.unsplash.com/photo-1561948955-570b270e7c36?w=300&q=60&auto=format&fit=crop'], user: 'Josefina Quiroga', userId: '11', likes: 38, views: 278, verified: false, source: 'manual' },
  { id: '12', type: 'adopcion', species: 'perro', name: 'Bruno', breed: 'Pastor alemán mestizo', color: 'Negro y fuego', size: 'grande', age: '4 años', gender: 'macho', zone: 'Barrio San Remo', address: 'Bº San Remo, Salta', lat: -24.819, lng: -65.412, date: '2025-04-28', reward: null, description: 'Bruno es un perro noble, fiel y muy protector. Necesita espacio para correr. Se lleva bien con niños.', phone: '387-4123789', photos: ['https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=300&q=60&auto=format&fit=crop'], user: 'Refugio Animal NOA', userId: '12', likes: 52, views: 445, verified: true, source: 'ong' },
  { id: '13', type: 'encontrado', species: 'gato', name: 'Sin nombre', breed: 'Mestizo', color: 'Negro', size: 'pequeño', age: 'Cachorro', gender: 'macho', zone: 'Barrio Belgrano', address: 'Bº Belgrano, Salta Capital', lat: -24.791, lng: -65.418, date: '2025-05-06', reward: null, description: 'Encontré este gatito negro de aprox. 3 meses debajo de un auto en Belgrano. Estaba solo y asustado.', phone: '387-4456789', photos: ['https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=300&q=60&auto=format&fit=crop'], user: 'Micaela Flores', userId: '13', likes: 27, views: 201, verified: false, source: 'manual' },
  { id: '14', type: 'perdido', species: 'perro', name: 'Firulais', breed: 'Salchicha', color: 'Marrón', size: 'pequeño', age: '7 años', gender: 'macho', zone: 'Barrio 20 de Febrero', address: 'Bº 20 de Febrero, Salta', lat: -24.778, lng: -65.432, date: '2025-05-03', reward: 'Sí – $5.000', description: 'Firulais es viejo y necesita medicación diaria. Si alguien lo ve, por favor avisar urgente. Tiene collar verde.', phone: '387-4678901', photos: ['https://images.unsplash.com/photo-1608096299210-db7e38487075?w=300&q=60&auto=format&fit=crop'], user: 'Ramón Sánchez', userId: '14', likes: 89, views: 712, verified: true, source: 'manual' },
  { id: '15', type: 'adopcion', species: 'gato', name: 'Nube', breed: 'Angora mestizo', color: 'Blanco y gris', size: 'mediano', age: '6 meses', gender: 'hembra', zone: 'Barrio Castañares', address: 'Bº Castañares, Salta', lat: -24.807, lng: -65.388, date: '2025-05-01', reward: null, description: 'Nube es una gatita muy juguetona y sociable. Primera vacuna dada. Busca hogar amoroso.', phone: '387-4234567', photos: ['https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=300&q=60&auto=format&fit=crop'], user: 'Amigos de los Gatos Salta', userId: '15', likes: 63, views: 488, verified: true, source: 'ong' },
]

export const ZONES = ['Todas las zonas','Centro Histórico','Barrio San Bernardo','Barrio Tres Ceibos','Barrio Limache','Barrio Santa Ana','Barrio Palermo','Barrio Primavera','Barrio 20 de Febrero','Barrio Belgrano','Barrio San Lorenzo','Barrio Castañares','Barrio San Remo','Villa Las Rosas','Barrio Portezuelo','Barrio La Florida']

export const TYPE_CONFIG = {
  perdido:    { label: 'Perdido',     color: '#FF4757', bg: '#FFF0F1', text: '#C0392B', icon: '🔴' },
  encontrado: { label: 'Encontrado',  color: '#3B82F6', bg: '#EFF6FF', text: '#1D4ED8', icon: '🔵' },
  adopcion:   { label: 'En Adopción', color: '#10B981', bg: '#ECFDF5', text: '#065F46', icon: '🟢' },
}

export const SOURCE_CONFIG = {
  manual:    { label: 'Usuario',    icon: '👤', color: '#6B7280' },
  ong:       { label: 'ONG',        icon: '🏠', color: '#10B981' },
  petfinder: { label: 'Petfinder',  icon: '🐾', color: '#FF6B2C' },
  reddit:    { label: 'Reddit',     icon: '🔗', color: '#FF4500' },
  adoptapet: { label: 'AdoptAPet',  icon: '💚', color: '#059669' },
  ai:        { label: 'IA detectó', icon: '🤖', color: '#8B5CF6' },
}
